### PR TITLE
Azure Functions Version Upgrade, Introduction of Azure KeyVault & Solutions for open Issues #10, #19

### PR DESCRIPTION
**Pull request by mreyeros**
- Upgraded Azure Functions version from v2 to v3
- Introduced Azure KeyVault deployment to store Zip Passwords
- Enhanced solution by implementing an IFileProcessor to handle processing of zip archives
- Introduced DotNetZip library to address open issues #10, #19; adding .rar support as well as support for handling password protected archives
- Corrected typo in readme
- Updated ARM template to account for Azure Key Vault deployment and ZipPassword secret

### CODE REVIEW

**Comment by FBoucher** [comment]
Thank look super cool @mreyeros !!!
While trying to run from my side I got some deployment error. I updated the ARM template to make it work.

I still have some issue when looking at the result file.
The content of the file looks "encripted"
This
`mreyeros is the author
Frank just merged`
became that: 
`)-«1Pÿ—vñ„š‡{Ÿ !Øûª;v°hïƒ¸Ä2@&ûxåß	]¸VÝö¥Ç°l´+ÉêÚ`

Any idea?
Also it look like the Secret is not being created in the deployment but I think it's because of the name. It should ONLY contain alphanumeric characters.

**Comment by mreyeros** [comment]
Let me take a quick look

**Comment by mreyeros** [comment]
Oh, correct, I believe that if we just have the name as ZipPassword it should work since the secret is defined as a child resource of the KeyVault resource.  If the secret were defined as a separate top level resource, then that syntax would have worked if combined with a dependsOn pointing back to the KeyVault resourceId

**Comment by FBoucher** [comment]
On the stream I created the secret manually just to test... 
The zipped file were created in the output folder, but like mentioned in the previous comment the text was all strange.

**Comment by mreyeros** [comment]
So I just tested the function again in my subscription.  I have a storage account with two containers; input-files and output-files.  I created a password protected zip file using the password value stored in the KeyVault secret and uploaded to the input-files container.

image

Started the function and confirmed that KeyVault access was established and that the ZipPassword secret was retrieved and stored in the SecretSettings.ZipPassword field.  Zip file was processed via the FileProcessor's "ProcessFile" method and was determined to be a password protected file and Password was applied from the SecretSettings.ZipPassword value.  Each file in the zip, in this case one file, was pushed to the destination container of "output-files".  Navigated to the output-files container and confirmed that the file was successfully stored and confirmed that viewing the document displays un-encrypted contents.

image

image

Perhaps since the ZipPassword was not successfully stored in KeyVault as part of the deployment, it was not available at the time of processing the zip files.  This could explain why the contents of the files were coming back encrypted for you.

**Comment by FBoucher** [comment]
I will redeploy. 
Also the file test.txt became test_txt
Are you sure the code contained in branch `dev` is the same as the one you are using?

**Comment by mreyeros** [comment]
Ok Frank, so I just watched the stream and first off, let me apologize for the poor state of that ARM template, should have done some more thorough testing of that deployment.  Secondly, I have updated the ARM template in my dev branch to account for the remaining issues that you were encountering and have validated that all resources are in fact deployed successfully and correctly.  I do see that there is a potential issue with the regular expression that I am using in the FileProcessor when saving the new file blob once it has been unzipped, it is causing the **"."** in the filename to be replaced with a dash when it shouldn't be.  I have confirmed and that is the reason why the file is displaying as unreadable characters when viewing the contents of the file.   The strange thing that I notice though is that running the function locally and pointing at the deployed container, I am not seeing the same behavior when the regular expression replaces the characters in the filename.  I will try to get to the bottom of this and will let you know.

**Comment by FBoucher** [comment]
Sorry It was closed by mistake. :)

**Comment by mreyeros** [comment]
Afternoon Frank, just pushed final changes and I believe that we should be good now.  I have gone ahead and updated the readme file to add some more detail about the supported features, which now include Azure KeyVault for safely/securely storing the zip password for use when uncompressing password protected zip files.  I am going to see if I could possibly work on adding support for other archive types in the coming days if time permits.

**Comment by mreyeros** [comment]
Good morning Frank, just pushed some more changes.  Solution should now support **.rar** archives.  Took the opportunity to refactor the solution a bit just to tidy things up in my implementation.  Let me know if this version works better for you.

**Comment by mreyeros** [comment]
Afternoon Frank, I updated the api version(s) in the ARM template and confirmed that the deployment does in fact complete, either when deploying to a new resource group or to an existing one.  Please let me know if you still have issues running the deployment.

**Comment by FBoucher** [comment]
@all-contributors add @mreyeros for code, maintenance, review

**Pull request merged**
