### PR TITLE
Fixes large file unzipping

### PR DESCRIPTION
**Pull request by msftph**
Large zip files over 2GB run out of memory due to the use of a MemoryStream. This change directly uses the blob stream to move the file instead of first copying it to memory. See issue #24 

Because it isn't copying to memory first, I assume this will also speed up the unzip and may address #18 . 

This change also tries to preserve the extension in the zipped file name. The updated regex passes through '.' dots to the output file name. 

This change also adds additional logging to show what files are being extracted.

### CODE REVIEW

**Comment by FBoucher** [comment]
Nice work @msftph
I will try it, and merge if it's all working :)

**Comment by FBoucher** [comment]
@msftph are you able to fix the conflicts?

**Comment by FBoucher** [comment]
Awesome works @msftph !
However, since the last merge, your version is not compatible. If you could move the code logic into the `ServiceCollectionExtensions` I will merge it.

**Comment by girisenji** [comment]
Hi @FBoucher @msftph Could one of you kindly resolve the conflict and merge?
I'd be happy to help, please let me know

**Comment by msftph** [comment]
Looking at the most recent changes, it appears you switched to streams in the ZipProcessor so the pull request is no longer needed.

**Pull request closed without merging**
